// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';
import {time} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddTodo(arg1:string):Promise<number>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<string>>;

export function GetTodoByID(arg1:number):Promise<todo.Todo>;

export function GetTodos():Promise<Array<todo.Todo>>;

export function MarkAllTodosCompleted():Promise<void>;

export function MarkAllTodosUncompleted():Promise<void>;

export function MarkTodoCompleted(arg1:number):Promise<void>;

export function MarkTodoUncompleted(arg1:number):Promise<void>;

export function TogleTodoCompleted(arg1:number):Promise<void>;

export function UpdateTodo(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:time.Time):Promise<void>;
