// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['todo']['TodoApp']['AddCategory'](arg1);
}

export function AddTodo(arg1) {
  return window['go']['todo']['TodoApp']['AddTodo'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['todo']['TodoApp']['DeleteCategory'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['todo']['TodoApp']['DeleteTodo'](arg1);
}

export function GetCategories() {
  return window['go']['todo']['TodoApp']['GetCategories']();
}

export function GetTodoByID(arg1) {
  return window['go']['todo']['TodoApp']['GetTodoByID'](arg1);
}

export function GetTodos() {
  return window['go']['todo']['TodoApp']['GetTodos']();
}

export function MarkAllTodosCompleted() {
  return window['go']['todo']['TodoApp']['MarkAllTodosCompleted']();
}

export function MarkAllTodosUncompleted() {
  return window['go']['todo']['TodoApp']['MarkAllTodosUncompleted']();
}

export function MarkTodoCompleted(arg1) {
  return window['go']['todo']['TodoApp']['MarkTodoCompleted'](arg1);
}

export function MarkTodoUncompleted(arg1) {
  return window['go']['todo']['TodoApp']['MarkTodoUncompleted'](arg1);
}

export function TogleTodoCompleted(arg1) {
  return window['go']['todo']['TodoApp']['TogleTodoCompleted'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['todo']['TodoApp']['UpdateTodo'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTodoCategory(arg1, arg2) {
  return window['go']['todo']['TodoApp']['UpdateTodoCategory'](arg1, arg2);
}

export function UpdateTodoDeadline(arg1, arg2) {
  return window['go']['todo']['TodoApp']['UpdateTodoDeadline'](arg1, arg2);
}
